# sql主机连接设置
host: localhost
user: root
password: Xwt985211

# 数据库设置
database: wx_data
charset: utf8mb4
basic_table: "基本信息"
basic_table_PK: "患者编号"
sub_table_fk: "患者编号"
recreate: NONE

# 爬虫脚本设置
download_directory: "data_to_mysql"
web: "https://als.ashermed.com/web/login"
web_user: xx
web_password: xx
web_driver_path: "D://chromedriver-win64//chromedriver.exe"
